version: "3.9"
services:
  db:
    image: postgres:15
    container_name: nail_visual_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nail_visual
    ports:
      - "5432:5432"          # наружу на localhost:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
